version: '3.4'

services:
  web:
    build:
      dockerfile: ./dockerfiles/Dockerfile
      context: .
    volumes:
      - ./src/:/app
    depends_on:
      - db
    ports:
      - ${NODE_PORT}:3333
  db:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: adonis
      MYSQL_USER: homestead
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    command: ["--default-authentication-plugin=mysql_native_password"]
    entrypoint: ['/entrypoint.sh', '--character-set-server=utf8', '--collation-server=utf8_general_ci']
    healthcheck:
      test: "/usr/bin/mysql --user=homestead --password=${DATABASE_PASSWORD} --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 2s
      retries: 5
    volumes:
      - ./db_data:/var/lib/mysql
      - ./log/mysql:/var/log/mysql
    ports:
      - ${DATABASE_PORT}:3306
    #    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
